<a href="https://colab.research.google.com/github/AdokkuSchool/dap-2024/blob/main/les03/rep.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторная работа №3. NumPy

**Выполнил:** Хамзин Адильбек Канатбекович
**Группа:** ИС-23-2


In [1]:
import numpy as np
np.version.version


'2.0.2'

In [2]:
print("1. Min/Max 10x10:")
Z = np.random.random((10, 10))
Zmin, Zmax = Z.min(), Z.max()
print(f"Min: {Zmin:.4f}, Max: {Zmax:.4f}\n")


1. Min/Max 10x10:
Min: 0.0064, Max: 0.9894



In [3]:
print("2. Chessboard:")
Z = np.zeros((8, 8), dtype=int)
Z[1::2, ::2] = 1
Z[::2, 1::2] = 1
print(Z, "\n")


2. Chessboard:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]] 



In [4]:
print("3. Negate 3-8:")
z = np.arange(11)
z[(z > 3) & (z < 8)] *= -1
print(z, "\n")


3. Negate 3-8:
[ 0  1  2  3 -4 -5 -6 -7  8  9 10] 



In [5]:
print("4. Subtract row mean:")
z = np.random.rand(5, 10)
mean = z.mean(axis=1, keepdims=True)
z_centered = z - mean
print(f"Original shape: {z.shape}, Result shape: {z_centered.shape}\n")


4. Subtract row mean:
Original shape: (5, 10), Result shape: (5, 10)



In [6]:
print("5. Swap rows:")
z = np.arange(25).reshape(5, 5)
z[[0, 1]] = z[[1, 0]]
print(z, "\n")


5. Swap rows:
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 



In [7]:
print("6. Polar coordinates:")
z = np.random.random((10, 2))
X, Y = z[:, 0], z[:, 1]
R = np.sqrt(X**2 + Y**2)
P = np.arctan2(Y, X)
print(f"R (first 3): {R[:3]}")
print(f"P (first 3): {P[:3]}\n")


6. Polar coordinates:
R (first 3): [0.73668819 0.31588441 0.49400893]
P (first 3): [0.29537753 0.87394147 1.37841167]



In [8]:
print("7. Max -> 0:")
z = np.random.random(10)
z[z.argmax()] = 0
print(z, "\n")


7. Max -> 0:
[0.47061128 0.1531411  0.85097517 0.01890525 0.22780514 0.52680578
 0.         0.43565719 0.22734619 0.89335044] 



In [9]:
print("8. Add 1 at indices (unique):")
z = np.ones(10)
i = np.random.randint(0, len(z), 20)
z[np.unique(i)] += 1
print(z, "\n")


8. Add 1 at indices (unique):
[2. 2. 1. 2. 1. 2. 2. 1. 1. 2.] 



In [10]:
print("9. Insert zeros:")
z = np.array([1, 2, 3, 4, 5])
nz = 3
z0 = np.zeros(len(z) + (len(z)-1)*nz)
z0[::nz+1] = z
print(z0, "\n")


9. Insert zeros:
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.] 



In [11]:
print("10. Nearest value:")
z = np.arange(100)
v = np.random.uniform(0, 100)
index = (np.abs(z - v)).argmin()
print(f"Target: {v:.2f}, Nearest: {z[index]}")


10. Nearest value:
Target: 21.75, Nearest: 22


## Ответы на контрольные вопросы


Типы данных (dtype):

[1, 4, 2] -> int64
[1., 4, 2] -> float64
dtype='str' -> unicode string (<U)
dtype='bool' -> boolean
[1, 0, 1j] -> complex128
Вывод в консоль:

Сложение строки и числа в dtype='str' приводит к конкатенации строк ('4' + '1' = '41').
Булевы операции над массивами работают поэлементно или через методы any/all.
Преобразование комплексных чисел в int вызывает ошибку.
Результат операций:

np.ones - массив единиц.
np.linspace - равномерное разбиение отрезка.
np.eye - единичная матрица.
np.random.random - случайные числа [0, 1).
Срезы (Slicing):

X[0,0] - элемент в левом верхнем углу.
X[:,:] - копия всего массива.
X[::-1, ::-1] - поворот массива на 180 градусов.
np.split:

Различие в параметре axis: разделение по строкам (0) или по столбцам (1).
Списки vs NumPy:

Списки (list + list) склеиваются.
Массивы NumPy (arr + arr) складываются математически.
Измерение времени:

Используется магическая команда %time или %timeit.
np.sum:

axis=0 - сумма столбцов.
axis=1 - сумма строк.
Булевы маски:

X > 3 возвращает массив True/False.
X[X > 3] возвращает только те элементы, которые удовлетворяют условию.
Преимущества NumPy:

Высокая скорость за счет реализации на C.
Эффективное использование памяти (один тип данных).
Векторизация операций (без циклов Python).